#!/bin/bash -eux

# A Weave Cloud user is usually expect to install the agents using one simple command like this:
#   kubectl create -n kube-system 'https://cloud.weave.works/k8s/v1.6/weave-cloud?t=<service_token>'
#
# There is service that generates manifest based on the parameters passed in the URL.
# This chart simply checks-in the YAML manifest generated by the service, and this script is used to
# update the chart.

url="https://frontend.dev.weave.works/k8s/v1.6/flux"

get_manifest=(
  curl --silent --location
    --get "${url}"
    --data-urlencode "flux-version=1.0.0"
    --data-urlencode "omit-support-info=true"
    --data-urlencode "git-url={{.Values.Git.URL}}"
    --data-urlencode "git-branch={{.Values.Git.Branch}}"
    --data-urlencode "git-path={{.Values.Git.Path}}"
)

standalone="$("${get_manifest[@]}")"
hosted="$("${get_manifest[@]}" --data-urlencode "service-token={{.Values.WeaveCloud.ServiceToken}}")"

cat << EOF > "./templates/flux-hosted.yaml"
{{- if not (empty .Values.WeaveCloud.ServiceToken) -}}
${hosted}
{{- end -}}
EOF

cat << EOF > "./templates/flux-standalone.yaml"
{{- if empty .Values.WeaveCloud.ServiceToken -}}
${standalone}
{{- end -}}
EOF
